### ISSUE TITLE
Question about the usage of some env variables

### ISSUE THREAD

**Issue by ovizii** [guillaumeaubert/gmvault-docker#11]
Does this look right inside my docker-compose.yml? Trying to use "-c no" so no emails will be deleted locally to create an email archive.

```
environment:
  - GMVAULT_OPTIONS="-c no --no-compression"
```
**Is there an option to run a full sync with "-c yes" MANUALLY?**

> GMVAULT_SYNC_ON_STARTUP 

What type of sync does this trigger? I assume it would do a "gmvault sync -t full" as that is the default?
**EDIT:** I tested it and the sync on startup is a quick sync.

> GMVAULT_QUICK_SYNC_SCHEDULE and GMVAULT_FULL_SYNC_SCHEDULE 

What variables/form can this take? (Answered my own question after looking at Dockerfile. It takes standard cron expressions.)
```
	GMVAULT_FULL_SYNC_SCHEDULE="1 3 * * 0" \
	GMVAULT_QUICK_SYNC_SCHEDULE="1 2 * * 1-6" \
```

If I don't want to automatically run `GMVAULT_FULL_SYNC_SCHEDULE`, is there a more elegant manner than setting it to` 0 5 31 2 *` “At 05:00 on day-of-month 31 in February.” which basically means never?

**Comment by ovizii** [comment]
Here is my commented docker-compose.yml in case it helps anyone else.

```
version: '3.9'

services:

# https://github.com/guillaumeaubert/gmvault-docker

  gmvault:
    image: aubertg/gmvault-docker:latest
    container_name: gmvault
    hostname: gmvault
    tty: true
# tty: true is the equivalent of docker run -t 
    stdin_open: true
# stdin_open: true the equivalent of docker run -i but I am not sure if this is needed 
    networks:
      - gmvault
    volumes:
      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - /path/to/store/Email-archive:/data
    restart: "no"
    environment:
      - GMVAULT_UID=1000
      - GMVAULT_GID=1000
      - GMVAULT_EMAIL_ADDRESS=me@vanitydomain.tld
      - GMVAULT_SEND_REPORTS_TO=me@vanitydomain.tld
      - GMVAULT_TIMEZONE=Europe/Berlin
      - GMVAULT_OPTIONS=-c no --no-compression
# -c no does not deleted local emails when they have been deleted from Gmail, compression is unnecessary as ZFS does that already for me
      - GMVAULT_SYNC_ON_STARTUP=yes
# does a quick sync on startup
      - GMVAULT_QUICK_SYNC_SCHEDULE=1 2 2-31 * *
# at 02:01 on every day except the 1st of every month - quick sync only goes back the last 7 days
      - GMVAULT_FULL_SYNC_SCHEDULE=1 3 1 * *
# at 03:01 on the first day of the month - full sync goes through the full mailbox
    cpus: 1
    mem_limit: 1G
# cpu and mem limits seem enough for gmvault
networks:
  gmvault:
    external: true
    name: gmvault
```
